package:
    name: common2_x
    version: 0.2.0


source:
    path: ../

requirements:
    build:
       - python
       - numpy >=1.9
       - pandas >=0.15.2
       - setuptools

    run:
       - python
       - numpy >=1.9
       - pandas >=0.15.2
       - common1_x