package:
    name: common1_x
    version: 0.1.0


source:
    path: ../

requirements:
    build:
       - python
       - numpy >=1.9
       - pandas >=0.15.2
       - setuptools

    run:
       - python
       - numpy >=1.9
       - pandas >=0.15.2
       - nose
       - coverage