package:
    name: toplevel
    version: 1.0.0


source:
    path: ../

requirements:
    build:
       - python

    run:
       - python             2.7*
       - numpy              1.9.2                   py27_0
       - pandas             0.15.2                  np19py27_1
       - common1            0.1.0                   py27_0
       - common2            0.2.0                   py27_0
       # pandas dependencies
       - python-dateutil    2.4.1                   py27_0
       - pytz               2015.4                  py27_0
       - six                1.9.0                   py27_0
       # common1 dependencies
       - coverage           3.7.1                   py27_0
       - nose               1.3.7                   py27_0

