package:
    name: common1_y
    version: 0.1.0


source:
    path: ../

requirements:
    build:
       - python
       - numpy >=1.9
       - pandas >=0.15.2
       - setuptools

    run:
       - python
       - numpy              1.9.2                   py27_0
       - pandas             0.15.2                  np19py27_1
       - python-dateutil    2.4.1                   py27_0
       - pytz               2015.4                  py27_0
       - six                1.9.0                   py27_0
       - coverage           3.7.1                   py27_0
       - nose               1.3.7                   py27_0